Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus   = 1
    end

    
    config.vm.define "slave1.puppet" do |slave1|
        slave1.vm.network "forwarded_port", guest: 80, host: 8080
        slave1.vm.network "private_network", ip: "192.168.50.26"
        slave1.vm.hostname = "slave1.puppet"
    
        slave1.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.become = true
        end
    end

    config.vm.define "slave2.puppet" do |slave2|
        slave2.vm.network "forwarded_port", guest: 80, host: 8081
        slave2.vm.network "private_network", ip: "192.168.50.27"
        slave2.vm.hostname = "slave2.puppet"
    
        slave2.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.become = true
        end
    end

    config.vm.define "master.puppet", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.50.25"
        master.vm.hostname = "master.puppet"
        master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.limit = 'master,slaves'
            ansible.inventory_path = "inventory"
            ansible.become = true
        end
    end


end