Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8080, host: 8081

    config.vm.provider "virtualbox" do |vb|
        vb.name = "hometask1_box"
        # Customize the amount of memory on the VM:
        vb.memory = "512"
    end
    
    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2 php php-fpm libapache2-mod-php
        systemctl enable apache2
        mkdir /var/www/php/
        rm /var/www/html/index.html
        curl https://raw.githubusercontent.com/Fenikks/devops-files/master/02-tools/files/index.html -o /var/www/html/index.html
        curl https://raw.githubusercontent.com/Fenikks/devops-files/master/02-tools/files/index.php -o /var/www/php/index.php
        echo "Listen 8080" >> /etc/apache2/ports.conf
        echo -e "<VirtualHost *:8080>\n        ServerAdmin webmaster@localhost\n        DocumentRoot /var/www/php\n        ErrorLog ${APACHE_LOG_DIR}/error.log\n        CustomLog ${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>" >> /etc/apache2/sites-available/000-default.conf
        service apache2 restart
    SHELL
end