Vagrant.configure("2") do |config|
    config.vm.box = "aliakseit/devops-hometask-01"
    config.vm.box_version = "01.beta"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8080, host: 8081

    config.vm.provider "virtualbox" do |vb|
        vb.name = "hometask1-box2"
        # Customize the amount of memory on the VM:
        vb.memory = "512"
    end

    config.vm.provision "shell", inline: <<-SHELL
        mkdir /var/www/php
        cp /vagrant/conf/test-php-page.conf /etc/httpd/conf.d/test-php-page.conf
        cp /vagrant/pages/index.php /var/www/php/index.php
        cp /vagrant/pages/index.html /var/www/html/index.html
        chmod 644 /etc/httpd/conf.d/test-php-page.conf
        chmod 644 /var/www/php/index.php
        chmod 644 /var/www/html/index.html
        firewall-cmd --permanent --add-service=http
        firewall-cmd --permanent --add-port=8080/tcp
        firewall-cmd --reload
        echo "Listen 8080" >> /etc/httpd/conf/httpd.conf
        systemctl restart httpd
    SHELL
end