name: Create WCG docker image
run-name: ${{ github.actor }} start creating WCG docker image
on:
  workflow_dispatch:
  push:
jobs:
  Build-wcg-image:
    runs-on: self-hosted
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
      - name: Build wcg docker image 
        run: cd ./11-github-actions && ls -la
