name: Create WCG docker image
run-name: ${{ github.actor }} start creating WCG docker image
on:
  workflow_dispatch:
  push:
jobs:
  Build-wcg-image:
    runs-on: self-hosted
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        with:
          repository: AlTriV/devops-hometasks
      - name: Build wcg docker image 
        run: |
          cd ./11-github-actions
          OWNER=$(echo ${{ env.GITHUB_REPOSITORY_OWNER }} | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER/wcg:latest -t ghcr.io/$OWNER/wcg:${{ github.sha }} -f ./Dockerfile.multi .
