name: Create WCG docker image
run-name: ${{ github.actor }} start creating WCG docker image
on:
  workflow_dispatch:
  push:
jobs:
  Build-wcg-image:
    runs-on: self-hosted
    steps:
      - run: ls ${{ github.repository }}
