name: Create WCG docker image
run-name: ${{ github.actor }} start creating WCG docker image
on:
  workflow_dispatch:
  push:
jobs:
  build-wcg-image:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        with:
          repository: AlTriV/devops-hometasks
      - name: Build wcg docker image 
        id: wcg_build
        run: |
          cd ./11-github-actions
          OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          docker build -t wcg:latest -t ghcr.io/$OWNER/wcg:latest -t ghcr.io/$OWNER/wcg:${{ github.sha }} -f ./Dockerfile.multi . 
      - name: Deploy wcg docker image
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u $OWNER --password-stdin
          docker push ghcr.io/$OWNER/wcg:latest
          docker push ghcr.io/$OWNER/wcg:${{ github.sha }}
