name: Create WCG docker image
run-name: ${{ github.actor }} start creating WCG docker image
on:
  workflow_dispatch:
  push:
jobs:
  build-wcg-image:
    runs-on: self-hosted
    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v3
        with:
          repository: AlTriV/devops-hometasks
      - name: Build wcg docker image 
        run: |
          cd ./11-github-actions
          OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          docker build -t wcg:latest -t ghcr.io/$OWNER/wcg:latest -t ghcr.io/$OWNER/wcg:${{ github.sha }} -f ./Dockerfile.multi . 
  
  deploy-wcg-image:
    needs: build-wcg-image
    runs-on: self-hosted
    steps:
      - name: Connect to GitHub registry
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')
          echo ${{ secrets.ACTION_TOKEN }} | docker login ghcr.io -u $OWNER --password-stdin
      - name: Upload wcg docker image
        run: |
          docker push ghcr.io/$OWNER/wcg:latest
          docker push ghcr.io/$OWNER/wcg:${{ github.sha }}
